<?php

// Marcas disponibles al publicar (autos, motos, camiones, buses y maquinaria agrícola).
return [
    'Audi',
    'Baic',
    'BMW',
    'BYD',
    'Case IH',
    'Changan',
    'Chery',
    'Chevrolet',
    'Citroën',
    'Claas',
    'DFSK',
    'Dodge',
    'Dongfeng',
    'Fiat',
    'Ford',
    'Foton',
    'Freightliner',
    'Geely',
    'Great Wall',
    'Harley-Davidson',
    'Haval',
    'Hino',
    'Honda',
    'Hyundai',
    'International',
    'Isuzu',
    'Iveco',
    'JAC',
    'Jeep',
    'JMC',
    'John Deere',
    'Kawasaki',
    'Kia',
    'KTM',
    'Kubota',
    'Landini',
    'Land Rover',
    'Mahindra',
    'MAN',
    'Massey Ferguson',
    'Maxus',
    'Mazda',
    'Mercedes-Benz',
    'MG',
    'Mini',
    'Mitsubishi',
    'New Holland',
    'Nissan',
    'Opel',
    'Peugeot',
    'Porsche',
    'Ram',
    'Renault',
    'Royal Enfield',
    'Scania',
    'SsangYong',
    'Subaru',
    'Suzuki',
    'Tesla',
    'Toyota',
    'Valtra',
    'Volkswagen',
    'Volvo',
    'Yamaha',
    'Yutong',
    'Otra',
];
